/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { insightsGetInsights } from "../funcs/insightsGetInsights.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Insights extends ClientSDK {
  /**
   * Insights API Deep Dive
   *
   * @remarks
   * Returns taste-based insights based on the input parameters you provide.
   */
  async getInsights(
    request: operations.GetInsightsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetInsightsResponse> {
    return unwrapAsync(insightsGetInsights(
      this,
      request,
      options,
    ));
  }
}
