/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Audiences } from "./audiences.js";
import { Insights } from "./insights.js";
import { Tags } from "./tags.js";

export class Qloo extends ClientSDK {
  private _insights?: Insights;
  get insights(): Insights {
    return (this._insights ??= new Insights(this._options));
  }

  private _audiences?: Audiences;
  get audiences(): Audiences {
    return (this._audiences ??= new Audiences(this._options));
  }

  private _tags?: Tags;
  get tags(): Tags {
    return (this._tags ??= new Tags(this._options));
  }
}
